import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per platform, each generated from its folder under docs/.
// Ordering comes from sidebar_position front matter and _category_.json files.
// The generated API reference has its own docs instance and sidebar (api-sidebars.ts).
const sidebars: SidebarsConfig = {
  unity: [{type: 'autogenerated', dirName: 'unity'}],
  web: [{type: 'autogenerated', dirName: 'web'}],
};

export default sidebars;
